CREATE TABLE ITEMS
(
	ID NUMBER NOT NULL ENABLE,
	CONSTRAINT ITEM_PK PRIMARY KEY (ID),
	NAME NVARCHAR2(100) NOT NULL,
	DATE_CREATED DATE,
	DATE_LAST_UPDATE DATE,
	DESCRIPTION NVARCHAR2(100) 
);